<script lang="ts">
	import type { CallQualityOption } from './types';
	let { microphoneMuted, videoState = 'off', quality, qualityOptions = [], mode = 'all', onToggleMicrophone, onToggleCamera, onToggleScreen, onLeave, onQualityChange }: { microphoneMuted: boolean; videoState?: 'camera' | 'screen' | 'off'; quality?: string; qualityOptions?: readonly CallQualityOption[]; mode?: 'all' | 'devices' | 'quality'; onToggleMicrophone: () => void; onToggleCamera: () => void; onToggleScreen: () => void; onLeave: () => void; onQualityChange?: (quality: string) => void } = $props();
	let deviceClass = $derived(mode === 'devices' ? 'h-12 w-12 min-w-12 rounded-full p-0 [&>span]:hidden [&>svg]:h-[1.15rem] [&>svg]:w-[1.15rem]' : '');
</script>

<nav class:devices-only={mode === 'devices'} class:quality-only={mode === 'quality'} class={`call-controls min-w-0 ${mode === 'devices' ? 'flex w-auto justify-center rounded-full border border-slate-800 bg-slate-900/92 p-2' : mode === 'quality' ? 'block w-full' : 'grid w-full grid-cols-3 gap-1.5 max-md:grid-cols-4'}`} aria-label={mode === 'quality' ? 'Screen quality' : 'Call controls'}>
	{#if mode !== 'quality'}
		<button class:active={!microphoneMuted} class={`flex min-w-20 items-center justify-center gap-1 rounded-lg border px-2.5 py-2 text-[.68rem] hover:border-cyan-400 hover:text-cyan-100 focus-visible:outline-none ${!microphoneMuted ? 'border-emerald-400/55 bg-emerald-950/35 text-emerald-200' : 'border-slate-700 bg-slate-800 text-slate-300'} ${deviceClass}`} type="button" aria-pressed={!microphoneMuted} aria-label={microphoneMuted ? 'Turn on microphone' : 'Mute microphone'} onclick={onToggleMicrophone}><svg class="h-4 w-4 flex-none fill-none stroke-current stroke-[1.7] [stroke-linecap:round] [stroke-linejoin:round]" aria-hidden="true" viewBox="0 0 24 24"><path d="M12 15a3 3 0 0 0 3-3V6a3 3 0 0 0-6 0v6a3 3 0 0 0 3 3Zm5-3a5 5 0 0 1-10 0m5 5v4m-3 0h6"/></svg><span class="max-[22rem]:hidden">Mic</span></button>
		<button class:active={videoState === 'camera'} class={`flex min-w-20 items-center justify-center gap-1 rounded-lg border px-2.5 py-2 text-[.68rem] hover:border-cyan-400 hover:text-cyan-100 focus-visible:outline-none ${videoState === 'camera' ? 'border-emerald-400/55 bg-emerald-950/35 text-emerald-200' : 'border-slate-700 bg-slate-800 text-slate-300'} ${deviceClass}`} type="button" aria-pressed={videoState === 'camera'} aria-label={videoState === 'camera' ? 'Turn off camera' : 'Turn on camera'} onclick={onToggleCamera}><svg class="h-4 w-4 flex-none fill-none stroke-current stroke-[1.7] [stroke-linecap:round] [stroke-linejoin:round]" aria-hidden="true" viewBox="0 0 24 24"><path d="M4 7.5A2.5 2.5 0 0 1 6.5 5h6A2.5 2.5 0 0 1 15 7.5v9a2.5 2.5 0 0 1-2.5 2.5h-6A2.5 2.5 0 0 1 4 16.5v-9ZM15 10l5-3v10l-5-3"/></svg><span class="max-[22rem]:hidden">Camera</span></button>
		<button class:screen={videoState === 'screen'} class={`flex min-w-20 items-center justify-center gap-1 rounded-lg border px-2.5 py-2 text-[.68rem] hover:border-cyan-400 hover:text-cyan-100 focus-visible:outline-none ${videoState === 'screen' ? 'border-violet-500/55 bg-violet-950/28 text-violet-200' : 'border-slate-700 bg-slate-800 text-slate-300'} ${deviceClass}`} type="button" aria-pressed={videoState === 'screen'} aria-label={videoState === 'screen' ? 'Stop sharing screen' : 'Share screen'} onclick={onToggleScreen}><svg class="h-4 w-4 flex-none fill-none stroke-current stroke-[1.7] [stroke-linecap:round] [stroke-linejoin:round]" aria-hidden="true" viewBox="0 0 24 24"><path d="M4 5h16v11H4zM9 20h6m-3-4v4"/></svg><span class="max-[22rem]:hidden">Share</span></button>
		<button class={`leave flex min-w-20 items-center justify-center gap-1 rounded-lg border border-red-500/45 bg-red-900/42 px-2.5 py-2 text-[.68rem] text-red-200 hover:border-cyan-400 hover:text-cyan-100 focus-visible:outline-none ${deviceClass}`} type="button" aria-label="Leave call" onclick={onLeave}><svg class="h-4 w-4 flex-none fill-none stroke-current stroke-[1.7] [stroke-linecap:round] [stroke-linejoin:round]" aria-hidden="true" viewBox="0 0 24 24"><path d="M5 4l4 4-2 2a12 12 0 0 0 7 7l2-2 4 4-2 2c-1 1-3 1-4 0C8 17 5 14 3 10c-1-2-1-3 0-4l2-2Z"/></svg><span class="max-[22rem]:hidden">Leave</span></button>
	{/if}
	{#if mode !== 'devices' && qualityOptions.length}<label class="quality grid gap-1 text-[.65rem] text-slate-400"><span>Quality</span><select class="min-h-11 w-full rounded-lg border border-slate-700 bg-slate-800 px-2 text-[.68rem] text-slate-300" aria-label="Video quality" value={quality} onchange={(event) => onQualityChange?.(event.currentTarget.value)}>{#each qualityOptions as option (option.id)}<option value={option.id}>{option.label}</option>{/each}</select></label>{/if}
</nav>
