<script lang="ts">
	import { CallControls, CallGrid, type CallParticipant, type CallQualityOption } from '../call';
	import { ChatPanel, ChatUnreadBadge, type ChatMessage } from '../chat';
	let { roomId, inviteUrl, status, participants, local, chatOpen = $bindable(false), unread = 0, messages = [], microphoneMuted, videoState, quality, qualityOptions, error = '', onCopyInvite, onSendChat, onToggleMicrophone, onToggleCamera, onToggleScreen, onQualityChange, onLeave }: { roomId: string; inviteUrl: string; status: string; participants: readonly CallParticipant[]; local: CallParticipant; chatOpen?: boolean; unread?: number; messages?: readonly ChatMessage[]; microphoneMuted: boolean; videoState: 'camera' | 'screen' | 'off'; quality: string; qualityOptions: readonly CallQualityOption[]; error?: string; onCopyInvite: () => void; onSendChat: (text: string) => void; onToggleMicrophone: () => void; onToggleCamera: () => void; onToggleScreen: () => void; onQualityChange: (quality: string) => void; onLeave: () => void } = $props();
</script>

<main class:chat-open={chatOpen} class={`room-shell grid min-h-dvh grid-cols-1 overflow-visible bg-background lg:h-dvh lg:overflow-hidden ${chatOpen ? 'md:grid-cols-[18rem_minmax(0,1fr)_20rem]' : 'lg:grid-cols-[18rem_minmax(0,1fr)]'}`}>
	<aside class="app-sidebar order-2 flex min-h-0 flex-col border-t border-slate-800 bg-slate-900/78 lg:order-none lg:border-t-0 lg:border-r" aria-label="Application navigation">
		<div class="brand flex h-12 items-center justify-between border-b border-slate-800 px-4"><strong class="text-sm tracking-[.04em]">PeerCast</strong><span class="rounded bg-emerald-500/16 px-2 py-[.2rem] text-[.625rem] font-bold tracking-[.1em] text-emerald-300">CLIENT</span></div>
		<div class="sidebar-content grid min-h-0 flex-1 grid-cols-1 gap-4 overflow-visible p-3 md:grid-cols-2 lg:flex lg:flex-col lg:overflow-y-auto">
			<div><p class="side-label mb-2 text-[.625rem] font-bold uppercase tracking-[.14em] text-slate-500">Connection</p><div class="connection grid gap-1.5 rounded-lg bg-slate-800/58 p-2.5"><span class="status font-mono text-[.7rem] text-emerald-300">● {status}</span><span class="room-id break-all font-mono text-[.62rem] text-cyan-300">ROOM / {roomId}</span></div></div>
			<div><p class="side-label mb-2 text-[.625rem] font-bold uppercase tracking-[.14em] text-slate-500">Participants ({participants.length + 1})</p><ul class="m-0 list-none p-0"><li class="flex min-w-0 items-center gap-1.5 border-b border-slate-800/70 py-2 text-xs text-slate-300"><i class="local-dot h-1.5 w-1.5 flex-none rounded-full bg-cyan-400"></i><span class="overflow-hidden text-ellipsis whitespace-nowrap">{local.displayName} (you)</span>{#if local.isHost}<em class="ml-auto text-[.62rem] not-italic text-emerald-300">Host</em>{/if}</li>{#each participants as participant (participant.id)}<li class="flex min-w-0 items-center gap-1.5 border-b border-slate-800/70 py-2 text-xs text-slate-300"><i class="h-1.5 w-1.5 flex-none rounded-full bg-purple-500"></i><span class="overflow-hidden text-ellipsis whitespace-nowrap">{participant.displayName}</span>{#if participant.isHost}<em class="ml-auto text-[.62rem] not-italic text-emerald-300">Host</em>{/if}</li>{/each}</ul></div>
			<div><p class="side-label mb-2 text-[.625rem] font-bold uppercase tracking-[.14em] text-slate-500">Invite link</p><label class="flex gap-1.5"><input class="min-w-0 flex-1 rounded-md border border-slate-700 bg-slate-900 p-2 font-mono text-[.65rem] text-cyan-300" readonly value={inviteUrl} aria-label="Invite link" onclick={(event) => event.currentTarget.select()} /><button class="cursor-pointer rounded-md border border-slate-700 bg-slate-800 px-2 py-1.5 text-[.68rem] text-slate-300 hover:border-cyan-400 hover:text-cyan-100 focus-visible:outline-2 focus-visible:outline-cyan-400" type="button" onclick={onCopyInvite} aria-label="Copy invite link">Copy</button></label></div>
			<div class="devices lg:mt-auto"><p class="side-label mb-2 text-[.625rem] font-bold uppercase tracking-[.14em] text-slate-500">Screen quality</p><CallControls mode="quality" {microphoneMuted} {videoState} {quality} {qualityOptions} onToggleMicrophone={onToggleMicrophone} onToggleCamera={onToggleCamera} onToggleScreen={onToggleScreen} onQualityChange={onQualityChange} onLeave={onLeave} /></div>
		</div>
		<div class="side-user mt-auto hidden items-center gap-2.5 border-t border-slate-800 p-3 lg:flex"><i class="grid aspect-square w-8 place-items-center rounded-full bg-slate-700 text-slate-400 not-italic">{local.displayName.slice(0, 1).toUpperCase() || '?'}</i><div class="min-w-0"><b class="block max-w-48 overflow-hidden text-ellipsis whitespace-nowrap text-xs">{local.displayName}</b><small class="mt-[.15rem] block max-w-48 overflow-hidden text-ellipsis whitespace-nowrap text-[.65rem] text-slate-500">{local.isHost ? 'Host' : 'Participant'}</small></div></div>
	</aside>
	<div class="room-main flex min-h-[75dvh] min-w-0 flex-col lg:min-h-0"><header class="app-header flex h-12 items-center border-b border-slate-800 bg-slate-900/45 px-3 lg:px-4"><h2 class="m-0 text-sm">Room</h2><span class="header-room ml-2 font-mono text-[.65rem] text-slate-500 max-md:hidden">{roomId}</span><div class="header-actions ml-auto"><button class="chat-toggle flex min-h-9 items-center gap-1.5 rounded-md px-2 text-xs text-slate-300 hover:bg-slate-800 focus-visible:bg-slate-800 focus-visible:outline-none" type="button" onclick={() => chatOpen = !chatOpen}>Chat <ChatUnreadBadge count={unread} /></button></div></header><section class="stage flex min-h-0 flex-1 flex-col overflow-auto p-2 lg:p-3"><CallGrid {local} {participants} />{#if error}<p class="error mt-3 mb-0 text-xs text-red-300" role="alert">{error}</p>{/if}<div class="stage-controls mt-3 flex justify-center"><CallControls mode="devices" {microphoneMuted} {videoState} {quality} {qualityOptions} onToggleMicrophone={onToggleMicrophone} onToggleCamera={onToggleCamera} onToggleScreen={onToggleScreen} onQualityChange={onQualityChange} onLeave={onLeave} /></div></section></div>
	<ChatPanel open={chatOpen} {messages} connected={status === 'connected'} onOpenChange={(open) => chatOpen = open} onSend={onSendChat} />
</main>
